### ISSUE TITLE
CHANGELOG.md ?

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#108] opened 2016-09-07 11:57 UTC
_From @Ceane on January 23, 2015 20:3_

The Changelog is buried away on the site, would you consider moving it to the top of the repo?

_Copied from original issue: webpack/webpack#715_

**Comment by pksjce** [comment] 2016-09-07 11:58
_From @jkimbo on January 27, 2015 14:17_

+1

**Comment by pksjce** [comment] 2016-09-07 11:58
_From @DarkPark on February 2, 2015 9:33_

would be very nice to add such information in each [release](https://github.com/webpack/webpack/releases) as it's not clear how to migrate from version to version and are there any breaking changes

**Comment by pksjce** [comment] 2016-09-07 11:58
_From @warrenrumak on February 6, 2015 23:45_

+1, changelogs and release notes are vital to the principles of open source software. It should be considered a point of pride to show off the work you've done, not a chore.

**Comment by pksjce** [comment] 2016-09-07 11:58
_From @warrenrumak on November 18, 2015 4:3_

Is closing this with no comment an acknowledgement that the webpack authors have chosen to not have a CHANGELOG.md file like most other popular open-source projects?

**Comment by pksjce** [comment] 2016-09-07 11:58
_From @DarkPark on November 18, 2015 8:14_

very strange decision

**Comment by pksjce** [comment] 2016-09-07 11:58
_From @Ceane on November 20, 2015 23:21_

I closed it because no one took it up. I should have done this a while back but now I am submitting two top level CHANGELOGs to the repo, one for 1.12.0 and above and one for pre 1.12 releases. The regular CHANGELOG.md is will mirror the format of Babel's CHANGELOG and the other one with older releases will mirror the existing CHANGELOG. Seeing that there are tons of releases, I did not go back and retroactively add in details to the older one, so anyone who wants to volunteer can do so. 

@sokra Not sure if you want to be in on this, however I will volunteer to update the CHANGELOG.md for future releases, minor and major.

Here's the PR for reference: https://github.com/webpack/webpack/pull/1658

**Comment by pksjce** [comment] 2016-09-07 11:58
_From @sokra on November 21, 2015 20:32_

Is it really a problem for you that the changelog is a [wiki page](http://webpack.github.io/docs/changelog.html) instead of a markdown in the repo?

For me it is easier to have it in the wiki, because a changelog in the repo would force me to update it with every release and I don't have the time to do this. I would rather update it in batches when I have the time to do it...

**Comment by pksjce** [comment] 2016-09-07 11:58
_From @DarkPark on November 22, 2015 9:20_

It's not a problem as long as there is a changelog somewhere.
Though there is a common way to have `changelog.md` in the project root or history details in each release (e.g. https://github.com/DarkPark/stb/releases)

**Comment by pksjce** [comment] 2016-09-07 11:58
_From @warrenrumak on November 22, 2015 19:45_

@sokra Whether it's easy for you to maintain is not the issue here.  You're building software that other people use and depend on.  It's time to think about how the work you do is presented and understood by others, not just what is personally convenient and saves you, what, a few minutes a month, if that?

Those of us who build applications for a living deal with dozens of packages at a time, and the question of whether or not we're going to upgrade to a newer version is based on the information that package presents about what new features, bug fixes and changes are included.  It's very frustrating and time-wasting to have to review every commit to decide whether or not it's safe to upgrade.

As for the contention that "the changelog is on the website".... No.  People don't like digging through tons of different web sites to find changelogs.  Every web site has its own structure, and certainly there've been cases where the web site wasn't updated by the time the release went out.  (I've encountered this with Webpack multiple times this year)  .... Coffeescript, for instance, hides their changelog 75% of the way down a massive, unusable homepage.  They release new versions just twice a year... am I supposed to remember where their changelog is everytime I see a new version is available in npm?  Ugh.  No.

With Angular, Aurelia, Gulp, Browserify, Karma, Bower, npm, and even node.js itself, it's very simple and consistent:  the changelog is in the repository, either in the root directory or in a documentation subdirectory.  Npm always includes changelog files when creating packages even if you don't specify it in the files glob -- that's how important they think it is.  Most of those projects take it a step further and directly link the description of the changes to the pull requests so that people interested in seeing how a specific change was implemented can read the code.

Have a look at how those projects document what they do, and think about whether you trust those projects more because of it.

**Comment by pksjce** [comment] 2016-09-07 11:58
_From @sapegin on November 23, 2015 13:48_

And don’t forget about tools like [npm-upgrade](https://github.com/th0r/npm-upgrade) which open change logs automatically. They couldn’t find change log somewhere in unusual location like a wiki on a site.

**Comment by pksjce** [comment] 2016-09-07 11:58
_From @mik01aj on November 23, 2015 15:50_

+1. Release notifications from [Sibbell](https://sibbell.com/about/) will get more meaningful then. Right now they show the package description instead of the changes:

![image](https://cloud.githubusercontent.com/assets/3027415/11341357/78b3fe86-9202-11e5-8e17-5f31fb3353f7.png)

**Comment by pksjce** [comment] 2016-09-07 11:58
_From @Ceane on November 23, 2015 16:49_

@sokra The reason I introduced it is because it mirrors other open source projects and I think that the community here welcome this change, as I see less and less projects using Github Wiki pages. I really would like to thank you for this project, webpack has been a great tool. We're here to help, if allowed.

**Comment by pksjce** [comment] 2016-09-07 11:58
_From @leoselig on November 27, 2015 9:19_

+1 from our side too
webpack is awesome, maybe we can adjust the "public relations work" a little :P

**Comment by SpaceK33z** [comment] 2016-10-03 12:19
Dupe of #17.

**Closed** 2016-10-03 12:38 UTC
Labels: migrated
