### ISSUE TITLE
can't load homepage

### ISSUE THREAD

**Issue by feexon** [webpack/webpack.js.org#919] opened 2017-02-20 09:18 UTC
https://webpack.js.org/ can't load homepage in china

**Comment by skipjack** [comment] 2017-02-22 02:50
Can you elaborate? Are you seeing errors in the console?

**Comment by holi-java** [comment] 2017-02-24 18:49
@skipjack,I'm sorry,I'm too late to reply to you.there is a error in my browser below:
Uncaught TypeError: undefined is not a function c28ec4ef07b397f623f2e6b04eb5b55c.js:2

**Comment by skipjack** [comment] 2017-02-25 17:34
@holi-java ok no problem... can you share which browser version and OS you are on so we can try to replicate? Also if you could share the full stack trace that would be helpful as well.

**Comment by holi-java** [comment] 2017-02-27 15:48
My OS is ubuntu12.04,both firefox and chome browsers can't load homepage.the full stacktrace below:

a.value c28ec4ef07b397f623f2e6b04eb5b55c.js:2(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:2a.value c28ec4ef07b397f623f2e6b04eb5b55c.js:2N c28ec4ef07b397f623f2e6b04eb5b55c.js:1(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:1L c28ec4ef07b397f623f2e6b04eb5b55c.js:2A c28ec4ef07b397f623f2e6b04eb5b55c.js:2D c28ec4ef07b397f623f2e6b04eb5b55c.js:2C c28ec4ef07b397f623f2e6b04eb5b55c.js:2E c28ec4ef07b397f623f2e6b04eb5b55c.js:2W c28ec4ef07b397f623f2e6b04eb5b55c.js:2i c28ec4ef07b397f623f2e6b04eb5b55c.js:1(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:1t c28ec4ef07b397f623f2e6b04eb5b55c.js:1(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:1(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:1(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:1(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:1

**Comment by holi-java** [comment] 2017-02-27 15:49
My OS is ubuntu12.04,both firefox and chome browsers can't load homepage.the full stacktrace below:
```
a.value c28ec4ef07b397f623f2e6b04eb5b55c.js:2(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:2a.value c28ec4ef07b397f623f2e6b04eb5b55c.js:2N c28ec4ef07b397f623f2e6b04eb5b55c.js:1(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:1L c28ec4ef07b397f623f2e6b04eb5b55c.js:2A c28ec4ef07b397f623f2e6b04eb5b55c.js:2D c28ec4ef07b397f623f2e6b04eb5b55c.js:2C c28ec4ef07b397f623f2e6b04eb5b55c.js:2E c28ec4ef07b397f623f2e6b04eb5b55c.js:2W c28ec4ef07b397f623f2e6b04eb5b55c.js:2i c28ec4ef07b397f623f2e6b04eb5b55c.js:1(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:1t c28ec4ef07b397f623f2e6b04eb5b55c.js:1(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:1(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:1(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:1(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:1
```

**Comment by holi-java** [comment] 2017-02-27 15:50
My OS is ubuntu12.04,both firefox and chome browsers can't load homepage.the full stacktrace below:

a.value c28ec4ef07b397f623f2e6b04eb5b55c.js:2(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:2a.value c28ec4ef07b397f623f2e6b04eb5b55c.js:2N c28ec4ef07b397f623f2e6b04eb5b55c.js:1(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:1L c28ec4ef07b397f623f2e6b04eb5b55c.js:2A c28ec4ef07b397f623f2e6b04eb5b55c.js:2D c28ec4ef07b397f623f2e6b04eb5b55c.js:2C c28ec4ef07b397f623f2e6b04eb5b55c.js:2E c28ec4ef07b397f623f2e6b04eb5b55c.js:2W c28ec4ef07b397f623f2e6b04eb5b55c.js:2i c28ec4ef07b397f623f2e6b04eb5b55c.js:1(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:1t c28ec4ef07b397f623f2e6b04eb5b55c.js:1(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:1(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:1(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:1(anonymous function) c28ec4ef07b397f623f2e6b04eb5b55c.js:1

**Comment by bebraw** [comment] 2017-02-28 03:51
That doesn't tell a lot. Could you examine the code to see where it fails?

Can anyone confirm this? More/better information is needed.

**Comment by skipjack** [comment] 2017-02-28 05:53
Yeah, @holi-java it would be great if you could pull the repo and 'npm start' it to try to get a better stack trace. I'm not sure any of us have an ubuntu environment to easily set up and test on.

**Comment by holi-java** [comment] 2017-02-28 13:28
@bebraw I want give you more clearly stack errors,but I can't download the source map in browser,it's not found.
@skipjack  yes,I have do it,but I found I can't install it in ubuntu,because something depends on mac os.

**Comment by skipjack** [comment] 2017-04-29 06:05
@holi-java tested on an ubuntu instance in firefox and the page loaded ok:

![image](https://cloud.githubusercontent.com/assets/8988697/25553408/36fc65cc-2c80-11e7-9bb1-8e9deb803cea.png)


even tested a few other pages and couldn't find any errors:

![image](https://cloud.githubusercontent.com/assets/8988697/25553402/1de84cb8-2c80-11e7-9df4-8e2567b4f639.png)


Unfortunately without being able to clearly reproduce, there's not much we can do about this. I have a feeling maybe the browser you're using is an older version we don't support or some other edge case error. I wish I could help more but I think we have to close this for now... if you give more details and we're able to reproduce I'd be happy to re-open.

**Closed by skipjack** 2017-04-29 06:05 UTC
Labels: Bug
