### ISSUE TITLE
Various issues with Getting Started page

### ISSUE THREAD

**Issue by francispotter** [webpack/webpack.js.org#486] opened 2016-12-12 00:45 UTC
I tried following the "Getting Started" steps from scratch, and ran into several problems, some of which may be newbie issues, or some might be actual flaws in the process.

1. "UNMET OPTIONAL DEPENDENCY" error on `npm install webpack --save`. It appears that webpack relies on something called fsevents, which only applies on OSX, so there's a warning message to us Linux users. Otherwise it seems to work, but the notice might be a little offputting to people just "getting started", and I wonder if there's a way to suppress the notification, or call it out in the docs so nobody is alarmed.
1. The `webpack` command doesn't work. After the installation, simply typing `webpack` results in "command not found" for me. Apparently there's some path trick to getting npm to create commands (I come from Ruby, where rvm just takes care of it). In any case, I actually have to do `./node_modules/.bin/webpack` to run the CLI, which took me a while to figure out. (I use zsh on Ubuntu, maybe it's another thing that "just works" on OSX?) Once again, I think it would be cool if the "getting started" docs explain this, but I personally don't really understand the issue well enough to explain it myself.
1. The diff for the HTML file is wrong. I think this is just a typo, or I'm misreading the diff, but I think the line `<script src="app/index.js"></script>` should be "minused" from within the body, not from the head.
1. The example simply doesn't work with webpack. Before using webpack, I can see the output. But when I run the webpack command to create `dist/bundle.js` as described here, it simply fails. Chrome console says "Uncaught SyntaxError: Unexpected token import"; mozilla.org says "This feature [import] is not implemented in any browsers natively at this time". Presumably if I add babel as a loader, or use some ES5-compatable version of "import" ("require"??) then it will work. So I'll go try to figure that out now. But in the meantime, the "Getting Started" instructions didn't really succeed in helping me to get started.
1. The instructions don't point out that you need a server if you're starting from scratch. I just did `npm install --save http-server` and then ran the server with `./node_modules/.bin/http-server` but it seems like including this in the docs would be helpful to other beginners.

I'd be glad to help make any of these edits to the docs myself, but I'm a little gun-shy since I am obviously even more of a beginner in this ecosystem than the docs are designed for.

**Comment by francispotter** [comment] 2016-12-12 00:53
My work is here; maybe someone can see the issues that I don't.

https://github.com/hgx/webpack-example/tree/not-working

**Comment by francispotter** [comment] 2016-12-12 00:54
Just to be clear - this is the instruction set I followed.

https://github.com/webpack/webpack.js.org/blob/959fe80b456eda77bfdbf1e28dbf13401c185252/content/get-started/index.md

**Comment by francispotter** [comment] 2016-12-12 00:58
Sure enough, if I change the `import` line to `var _ = require('lodash');` then it works (my issue 4 above). Is there some reason the example is using `import`?

**Comment by bebraw** [comment] 2016-12-12 17:02
> Sure enough, if I change the import line to var _ = require('lodash'); then it works (my issue 4 above). Is there some reason the example is using import?

`import` should work in webpack 2. The problem is that it's not out yet so you would have to install the beta. But once the final is out, the instructions should be valid.

**Comment by Flimm** [comment] 2016-12-21 14:46
@bebraw The fact that that webpack.js.org is for Webpack 2, which isn't even released yet, was not obvious at all. Your comment is very clarifying to me.

webpack.js.org is coming up in Google searches, so I think we need a banner on all webpack.js.org warning people about this (like the one in [Django dev docs](https://docs.djangoproject.com/en/dev/topics/forms/)).

**Comment by bebraw** [comment] 2016-12-21 14:48
@Flimm Can you PR that? There's `W>`. Another change for it - instead of `npm install webpack` do `npm install webpack@beta` in the quick start and add a little note there too.

**Comment by Flimm** [comment] 2017-01-01 13:38
@bebraw Looks like pull request #546 does what you requested.

**Comment by chrisVillanueva** [comment] 2017-01-04 19:49
I read through the "Getting Started" page and noticed some areas that could use a little more explanation. I made small text additions to help clarify the tutorial.  My changes can be viewed here:

https://github.com/chrisVillanueva/webpack.js.org/commit/97c0f2bfa07405c575551ddfb57a44e286dc7860

**Comment by bebraw** [comment] 2017-01-05 07:15
@chrisVillanueva Can you PR those changes? Thanks.

**Comment by chrisVillanueva** [comment] 2017-01-05 17:15
@bebraw PR is submitted.  Open to feedback.  Please let me know what I can do to help.  Thx

**Comment by bebraw** [comment] 2017-01-06 09:28
@francispotter The quick start has received quite a few changes. Feel free to review again.

**Comment by simon04** [comment] 2017-01-27 16:35
I'm referring to the items from the issue description:
1. has been clarified in #546
2. has been fixed in 4d041ae3b988d705bda44b29c7e8de2a7d195219, will be improved in #744
3. has been fixed in #512
4. this is an issue with using ES6, tracked as #713
5. a HTTP server is not needed; loading html/js files in the browser from the filesystem works.

So I think your issues are fixed, or tracked in more specific issues. Feel free to open a new issue when experiencing other/new problems.

**Closed by simon04** 2017-01-27 16:35 UTC
