### ISSUE TITLE
Better handling of page zoom / visibility of category links?

### ISSUE THREAD

**Issue by markerikson** [webpack/webpack.js.org#352] opened 2016-11-18 02:11 UTC
I normally have my browser's zoom level bumped up to about 120% or 130%.  When looking at the splash page for the new docs ( https://webpack.js.org/ ), I see two issues:

- When viewed at 1920x1080 but with 120% or 130% zoom, the links in the upper-right corner ("Documentation", "Guides") are pushed off the right side of the screen
- Even when at 100% zoom, those links are _very_ hard to see.  The text is small, and the gray font color is too close to the white/light-gray background.

I would suggest moving those links to the upper-left so they stay in place, and also making the links more visible by increasing the font size and changing the font color.

**Comment by skipjack** [comment] 2016-11-18 13:43
Hoping to get started on some updates to the color scheme this weekend, and then various components throughout the site to increase contrast, see #285, so hopefully that will address the contrast issue.

Not sure I agree with moving the links though, it looks like the breakpoints are working fine even when zooming I wasn't able to get to a state where any links were hidden. @SpaceK33z what do you think? @markerikson would you be able to share a screenshot highlighting the issue?

**Comment by SpaceK33z** [comment] 2016-11-18 13:54
I'm definitely +1 on changing the color schemes, the color scheme in #285 is definitely better and feels more "webpack-y" (and with that I mean that it matches more with the logo). I can give some feedback this weekend :).

About moving the links, even when zooming in it also worked fine for me. That said, moving it to the left might make a bit more sense because the sidebar is also on the left. Less mouse movement. But I'm fine with it either way.

**Comment by skipjack** [comment] 2017-02-02 23:06
Closing as the site has changed significantly since this was posted and we weren't able to reproduce the main issue. If anyone feels this is still a problem, feel free to re-open.

**Closed by skipjack** 2017-02-02 23:06 UTC
Labels: Bug, UI/UX
