### ISSUE TITLE
react Plugin for web 

### ISSUE THREAD

**Issue by madilraza** [webpack/webpack.js.org#3416] opened 2019-12-22 14:31 UTC
__Feature to document__

__Author(s)__

__Additional information__

[ ] I am willing to work on this issue and submit a pull request.

**Comment by anshumanv** [comment] 2019-12-22 18:02
Possibly duplicate of https://github.com/webpack/webpack.js.org/issues/3415

**Comment by montogeek** [comment] 2020-01-02 09:54
Please provide more information.

**Closed by montogeek** 2020-01-02 09:54 UTC
