### ISSUE TITLE
jsonpFunction not available in webpack 5

### ISSUE THREAD

**Issue by QuentinLuc** [webpack/webpack.js.org#3942] opened 2020-09-02 10:08 UTC
Hello!

I upgraded to webpack 5 and it seems jsonpFunction is not available anymore as an option in the Output section.  Has it been replaced or removed?  It still in the V5 documentation.

Here is the error I get during the build:
```
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.output has an unknown property 'jsonpFunction'. These properties are valid:
   object { assetModuleFilename?, auxiliaryComment?, charset?, chunkFilename?, chunkFormat?, chunkLoadTimeout?, chunkLoading?, chunkLoadingGlobal?, compareBeforeEmit?, crossOriginLoading?, devtoolFallbackModuleFilenameTemplate?, devtoolModuleFilenameTemplate?, devtoolNamespace?, ecmaVersion?, enabledChunkLoadingTypes?, enabledLibraryTypes?, filename?, globalObject?, hashDigest?, hashDigestLength?, hashFunction?, hashSalt?, hotUpdateChunkFilename?, hotUpdateGlobal?, hotUpdateMainFilename?, iife?, importFunctionName?, library?, libraryExport?, libraryTarget?, module?, path?, pathinfo?, publicPath?, scriptType?, sourceMapFilename?, sourcePrefix?, strictModuleExceptionHandling?, umdNamedDefine?, uniqueName?, webassemblyModuleFilename? }
   -> Options affecting the output of the compilation. `output` options tell webpack how to write the compiled files to disk.
   Did you mean output.chunkLoadingGlobal?

```

Thanks!

**Comment by evilebottnawi** [comment] 2020-09-02 10:11
Duplicate of #3940

> output.jsonpFunction -> output.chunkLoadingGlobal

**Closed by evilebottnawi** 2020-09-02 10:11 UTC
