### ISSUE TITLE
output.path is documented as "must be absolute", but can be relative

### ISSUE THREAD

**Issue by calaveraDeluxe** [webpack/webpack.js.org#674] opened 2017-01-18 14:49 UTC
The config option [output.path](https://webpack.js.org/configuration/output/#output-path) is documented as "must be absolute" (see also [https://webpack.js.org/configuration/#options](https://webpack.js.org/configuration/#options) and [https://webpack.js.org/concepts/output/#output-path](https://webpack.js.org/concepts/output/#output-path)). however, the following configuration containing  a relative path seems to work fine:
```javascript
module.exports = {
  entry: './app/index.js',
  output: {
    filename: 'bundle.js',
    path: './dist'
  }
}
```
In fact, that configuration is directly from the [getting started guide](https://webpack.js.org/get-started/#using-webpack-with-a-config).
Is this
* a documentation issue? (i.e. the path does not need to be absolute)
* a webpack issue? (i.e. the path needs to be absolute in some circumstances, and webpack should probably bark at you for using a relative one?)

**Comment by johnstew** [comment] 2017-01-24 04:58
> - a documentation issue? (i.e. the path does not need to be absolute)
I've had this working as a relative path as well in one of my configs. Doesn't seem to be an issue. I would think that it should be called out in the docs.

>- a webpack issue? (i.e. the path needs to be absolute in some circumstances, and webpack should probably bark at you for using a relative one?)

**Comment by SpaceK33z** [comment] 2017-01-24 10:31
The recommendation is to use an absolute path ([source](https://github.com/webpack/webpack/issues/1908#issuecomment-174172001)). webpack-dev-server and dev-middleware will throw an error if you use a relative path (see [this code](https://github.com/webpack/webpack-dev-middleware/blob/master/lib/Shared.js#L87-L89)).

**Comment by johnstew** [comment] 2017-01-24 15:50
I can confirm that in webpack-dev-server v2.2.0 it **does** throw an error if you do not use an absolute path. 

What can be a bit confusing though is that webpack v2.2.0 it **does not** throw the error. 

Since the recommendation is to have the absolute path then the docs should be updated to reflect that. 

So the [getting started](https://webpack.js.org/get-started/#using-webpack-with-a-config) page should be updated to use absolute path and also anywhere else its not using the recommended absolute path for `output.path`.

**Comment by bebraw** [comment] 2017-01-26 08:09
#728 was merged. Now the documentation should use absolute paths to avoid confusion.

**Comment by johnstew** [comment] 2017-01-26 15:02
@bebraw should this be closed now?

**Comment by bebraw** [comment] 2017-01-26 15:15
Yeah. Let's do that.

**Closed by bebraw** 2017-01-26 15:15 UTC

**Comment by thedonquixotic** [comment] 2018-06-20 00:12
It seems to me that this should be reopened. I'm very new to development and webpack but following a tutorial I have run into this absolute/relative path issue multiple times and the official documentation STILL shows the use of relative path in many of it's examples. This is very confusing as a newcomer.
