### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token , after applying the setup guide on "https://webpack.js.org/guides/getting-started"

### ISSUE THREAD

**Issue by ngodi** [webpack/webpack.js.org#3310] opened 2019-10-09 02:20 UTC
__Feature to document__

__Author(s)__

__Additional information__

[ ] I am willing to work on this issue and submit a pull request.

**Comment by ngodi** [comment] 2019-10-09 02:22
Had a fix by adding the meta tag in the html 
<!doctype html>
<html>
  <head>
    <title>Getting Started</title>
++    <meta charset="utf-8" >
  </head>
  <body>
    <script  src="main.js"></script>
  </body>
</html>

**Comment by EugeneHlushko** [comment] 2019-10-10 06:07
Hi @ngodi can you mention after which step and, which token was the issue? The html in the guide looks correct

**Comment by 16oh4** [comment] 2020-04-30 18:18
@ngodi @EugeneHlushko I had the same problem. It worked in Firefox, but in Chrome I got this error with the following HTML file:

**dist/index.html**
```html
<!DOCTYPE html>
<html>
    <head>
        <title>Getting started with webpack</title>
    </head>
    <body>
        <script src="./main.js"></script>
    </body>
</html>
```

**src/index.js**
```javascript
import _ from 'lodash';

function component() {
    const element = document.createElement('div');
    element.innerHTML = _.join(['Hello', 'webpack'], ' ');
    return element;
}

document.body.appendChild(component());
```

**package.json**
```json
{
  "name": "webpack",
  "private": true,
  "version": "1.0.0",
  "license": "MIT",
  "devDependencies": {
    "webpack": "^5.0.0-beta.15",
    "webpack-cli": "^3.3.11"
  },
  "dependencies": {
    "html-webpack-plugin": "^4.2.1",
    "lodash": "^4.17.15"
  }
}
```

**error in chrome console Version 81.0.4044.129 (Official Build) (64-bit) for Windows 10**
```bash
Uncaught SyntaxError: Invalid or unexpected token
```

**Fix by adding meta charset tag in dist/index.html**
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Getting started with webpack</title>
    </head>
    <body>
        <script src="./main.js"></script>
    </body>
</html>
```

**Please inform of this in the webpack getting started page at https://webpack.js.org/guides/getting-started/**

Thanks so much

**Comment by mehdirahimi** [comment] 2020-10-15 20:28
Just change `<!doctype html>` to `<!DOCTYPE html>` (uppercase).
another solution is just adding <meta tag of charset as @16oh4  said.

**Comment by PowerGlove** [comment] 2020-10-18 02:26
Thanks. This worked for me on Windows 10 64 bit. Added `<meta charset="utf-8"/>` and then the SyntaxError went away.

**Comment by ryanlelek** [comment] 2020-10-18 22:04
Thank you fellow Internet travelers!
I can confirm this fix works and docs need to be updated.

For those that find this via search, make sure you do a Hard Reload / Empty Cache if a basic refresh doesn't work

**Comment by zhtangsh** [comment] 2020-10-20 10:06
Adding `<meta charset="utf-8"/>` fixed this issue for me

**Comment by evilebottnawi** [comment] 2020-10-20 15:40
Answer https://github.com/webpack/webpack.js.org/issues/4081#issuecomment-712918078

@zhtangsh right solution

**Comment by chenxsan** [comment] 2020-10-30 15:02
I'm closing this issue now as we've [updated the documentation](https://github.com/webpack/webpack.js.org/pull/4070) regarding `<meta charset="utf-8"/>`. If anyone still has a problem, consider filing a new issue, thanks.

**Closed by chenxsan** 2020-10-30 15:02 UTC
Labels: Needs Clarification

**Comment by henrylow97** [comment] 2021-01-05 07:50
Cheers haha, thanks for the `<meta charset="utf-8"/>` answer. For my case I got the error when I'm using Webpack to build a React web widget with `mode: 'production'`, but when `mode: 'development'` it wont trigger such error.

**Comment by millefalcon** [comment] 2021-12-17 17:40
> Thank you fellow Internet travelers! I can confirm this fix works and docs need to be updated.
> 
> For those that find this via search, make sure you do a Hard Reload / Empty Cache if a basic refresh doesn't work

I was trying out webpack for the first time today, and I came across this issue. Though I added the meta tag and checked the source was getting updated, it didn't work out until I hit Hard Reload / Empty Cache. Thanks @ryanlelek

**Comment by elimisteve** [comment] 2022-08-11 00:42
For posterity: I ran into this error because I visited a Webpack-built site from a 3-year-old version of Chromium (v73 from 2019), where Webpack included an underscore in a Number, which only recently became valid.

"Solved" this by upgrading my browser.

**Comment by pomSense** [comment] 2022-10-26 00:57
Confirmed and working. For those use `html-webpack-plugin`, here is the template example:

```js
  plugins: [
      new HtmlWebpackPlugin({
        templateContent: `
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8" />
      </head>
      <body>
        <div id="root"></div>
      </body>
    </html>
  `
]
```
