### ISSUE TITLE
Main navigation submenu doesn't show

### ISSUE THREAD

**Issue by Munter** [webpack/webpack.js.org#2021] opened 2018-04-11 08:16 UTC
The main navigation has logic to show a submenu when a certain section of the page is active. This seems to never be triggered. https://github.com/webpack/webpack.js.org/blob/master/src/components/Navigation/Navigation.jsx#L76

**Comment by montogeek** [comment] 2018-04-11 09:30
Duplicate of https://github.com/webpack/webpack.js.org/issues/2019

**Closed by montogeek** 2018-04-11 09:30 UTC
