### ISSUE TITLE
Links on homepage are broken

### ISSUE THREAD

**Issue by Sm00g15** [webpack/webpack.js.org#2637] opened 2018-11-08 04:23 UTC
# Bug report

**What is the current behavior?**
Links that aren't responding to clicks on the homepage only at: https://webpack.js.org/

**If the current behavior is a bug, please provide the steps to reproduce.**
1) navigate to https://webpack.js.org/
2) attempt to click links in the navbar

**What is the expected behavior?**
One would expect the links to be clickable and then take me to another page

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: MacOS
Additional tools: [Browser]: Chrome

**UPDATED**

**Comment by byzyk** [comment] 2018-11-11 13:38
Hi @Sm00g15! Thanks for submitting the issue.

Would you mind share your OS and browser versions here?

**Comment by debs-obrien** [comment] 2018-12-09 17:06
I have just tested all links on MacOS and chrome and all seems to be working, perhaps it was a slow connection as the links in the top navbar do take a few seconds to load so on a slow connection perhaps it just didn't fully load at that moment. @Sm00g15 please check it again and if it is still not working can you tell us the exact link that isn't working. Thanks :)

**Comment by Sm00g15** [comment] 2018-12-10 00:30
hey @byzyk , sorry I didn't get back to you sooner! It's MacOS and Chrome. Here's a screen recording.
[Screen Recording 2018-12-10 at 1.28.08 PM.zip](https://github.com/webpack/webpack.js.org/files/2661182/Screen.Recording.2018-12-10.at.1.28.08.PM.zip)

**Comment by byzyk** [comment] 2018-12-10 07:12
@Sm00g15 thanks for getting back to me. It's indeed really weird.

Could you please try to test it in the incognito mode without any extensions enabled? Or just for the sake of the experiment try another browser (say Safari or Firefox). Also, it would help if you could share console output if there is any. 

Looking forward to hearing back from you.

**Comment by Sm00g15** [comment] 2018-12-10 08:52
@byzyk I've tested it in Safari and it works just fine there. However, I tested in Chrome again and Chrome Incognito-Mode and it's still not working. Here's the console output: 
![screen shot 2018-12-10 at 9 50 55 pm](https://user-images.githubusercontent.com/14209806/49720914-d2314000-fcc5-11e8-8154-24f4cdcc8ddb.jpg)

**Comment by byzyk** [comment] 2018-12-10 08:57
Form the video you shared it seems like some sort of overlay that prevents you from navigating. What version of Chrome are you using at the moment and have you tried to update it to the latest one?

**Comment by Sm00g15** [comment] 2018-12-10 08:59
Yeah seems like it, strange.

 ```
Google Chrome is up to date
Version 71.0.3578.80 (Official Build) (64-bit)
```

**Comment by EugeneHlushko** [comment] 2018-12-10 14:43
Hi @Sm00g15 
I think it is fixed in #2715

To reproduce your issue i had to resize my browser window to under 500px height. TY for reporting 👍

**Comment by montogeek** [comment] 2018-12-10 15:41
Deploy takes ~30 mins, please check again

**Closed** 2018-12-10 15:41 UTC
Labels: In Progress, UI/UX

**Comment by Sm00g15** [comment] 2018-12-10 18:05
@EugeneHlushko @montogeek yup, this worked. Well done guys

**Comment by debs-obrien** [comment] 2018-12-10 19:08
yeahhh. thanks for reporting @Sm00g15, glad we got it sorted.
