### ISSUE TITLE
Design is broken on Safari

### ISSUE THREAD

**Issue by alanhussey** [webpack/webpack.js.org#337] opened 2016-11-16 21:23 UTC
The redesign looks great! …but it's a bit broken on Safari :(

- the dependency graph is offset, and is missing the files
- the navigation in the top-right overflows off of the screen

![screen shot 2016-11-16 at 1 17 24 pm](https://cloud.githubusercontent.com/assets/383725/20366288/30781180-abff-11e6-9b84-dd801c858fc4.png)

In addition, the menu button is a bit off-screen when the viewport is small enough.

![screen shot 2016-11-16 at 1 24 05 pm](https://cloud.githubusercontent.com/assets/383725/20366442/f9ecb2f0-abff-11e6-8fb8-3835d7af635c.png)

I did a search for `"is:issue is:open safari"` and nothing relevant turned up. Please let me know if there's anything I can do to help repro this.

**Comment by skipjack** [comment] 2016-11-17 05:56
@alanhussey thanks for pointing this out, we'll try to address it soon and let you know if we can't reproduce. We have some other updates planned for this section of the splash page so this can fit right in to those 👍

**Comment by skipjack** [comment] 2016-11-20 16:47
Once 809739a1168 is cherry picked to develop this should be fixed.

**Comment by SpaceK33z** [comment] 2016-11-21 14:32
Should be fixed now.

**Closed by SpaceK33z** 2016-11-21 14:32 UTC
Labels: Bug, Interface
