### ISSUE TITLE
Webpack Public Path 404 from Google

### ISSUE THREAD

**Issue by spencerkordecki** [webpack/webpack.js.org#2935] opened 2019-04-12 01:03 UTC
I was searching for docs on `publicPath` through Google and the first result that is returned is a 404. It looks like Google is thinking the URL is `/guides/public-path/index.html` when it's actually just `/guides/public-path/`

404 URL: https://webpack.js.org/guides/public-path/index.html
Google URL: https://www.google.com/search?client=firefox-b-1-d&q=webpack+publicpath

Let me know if I can provide any further information.

**Comment by montogeek** [comment] 2019-04-12 08:54
@EugeneHlushko Uhmm, any idea?

**Comment by spencerkordecki** [comment] 2019-04-13 12:02
@montogeek I checked again today and I can't see that link through Google any more. Perhaps Google was crawling the wrong items at some point? That link still 404s, but I can only access it directly and not through Google like I was able to at the time of the issue.

**Comment by EugeneHlushko** [comment] 2019-04-13 18:05
Interesting, maybe this is one of google "features" where it also tries to get `index.html` file in the url...  I dont see internal links to .html files. Will have a second look later when i've time

**Comment by anshumanv** [comment] 2019-04-18 08:41
This seems fixed now.

**Comment by EugeneHlushko** [comment] 2019-04-18 09:41
Closing as i cannot reproduce either

**Closed by EugeneHlushko** 2019-04-18 09:41 UTC
Labels: SEO
