### ISSUE TITLE
Add TODO: prefix to ?> bits (CSS solution)

### ISSUE THREAD

**Issue by patrickkettner** [webpack/webpack.js.org#729] opened 2017-01-26 07:51 UTC
https://github.com/webpack/webpack.js.org/blame/124651da0a495f788ffdce68f6152b27dc7d4da7/content/guides/migrating.md#L299

![image](https://cloud.githubusercontent.com/assets/465414/22323658/307c985e-e359-11e6-8c78-09a2866ab611.png)

**Comment by bebraw** [comment] 2017-01-26 08:05
Yeah. That should probably link [here](https://webpack.js.org/configuration/module/#module-contexts). That `?>` syntax means it's a TODO. PR welcome.

**Comment by rouzbeh84** [comment] 2017-01-26 21:16
[module-contexts](https://webpack.js.org/configuration/module/#module-contexts) section has been marked as `deprecated`. Should it just be removed as well as the marking the deprecated line with a `W>`?

**Comment by patrickkettner** [comment] 2017-01-26 23:45
@bebraw should the parser be made aware to ignore lines that begin with `?>`?

**Comment by bebraw** [comment] 2017-01-27 05:20
@rouzbeh84 Good point. The context bit is weird and feels a little out of place. I agree a warning would work better there. I guess the intended article doesn't exist yet.

@patrickkettner No need. It works that way by design. There's some custom syntax in place.

**Comment by patrickkettner** [comment] 2017-01-27 08:10
@bebraw not sure I follow. the website shows the exact text, which seems like a mistake

**Comment by bebraw** [comment] 2017-01-27 08:17
@patrickkettner Ok. Feel free to PR. I'm missing something obvious here. The TODOs are visible at the site on purpose.

**Comment by patrickkettner** [comment] 2017-01-27 08:27
ah! my misunderstanding then. I meant as a user it feels like a mistake. but if it is intentional, then no worries! feel free to close :]

**Comment by bebraw** [comment] 2017-01-27 08:31
@patrickkettner It could be cool to add **TODO:** prefix to make this clearer. I think it would be possible to pull that off with a bit of CSS. I'll leave this open till that is done. 👍

**Closed** 2017-02-02 16:19 UTC
Labels: Enhancement, UI/UX
